name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-branch:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    timeout-minutes: 2
    concurrency:
      group: check-pr-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if the PR's branch is updated
        uses: osl-incubator/gh-check-pr-is-updated@1.0.0
        with:
          remote_branch: origin/main
          pr_sha: ${{ github.event.pull_request.head.sha }}

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: ci-${{ github.event_name }}-${{ github.ref }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install uv

      - name: Create virtual environment
        run: uv venv .venv

      - name: Activate virtual environment
        run: source .venv/bin/activate

      - name: Install build-system
        run: pip install -r requirements.txt

      - name: Install dependencies
        run: |
          uv pip install -e .[dev]
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run tests
        run: |
          # add your command for running tests here

      - name: Run style checks
        if: success() || failure()
        run: |
          export PATH="$(uv venv bin):$PATH"
          pre-commit install
          pre-commit run --all-files
